# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Sergio Pacheco
tagline:          'Blog'
description:      'Sergio Pacheco Blog'
url:              https://sergiopacheco.github.io
baseurl:          '/lany' 

author:
  name:           'Sergio Pacheco'
  url:            https://sergiopacheco.github.io
  
gems:             [jekyll-paginate]  

paginate:         5

# paginate_path:    'page:num'
paginate_path:    'lany/:num'

# Custom vars
version:          2.0.0

github:
  repo:          https://github.com/SergioPacheco/lany
